### ISSUE TITLE
Can't create GUI.container without error

### ISSUE THREAD

**Issue by StrangeOne101** [IgorTimofeev/OpenComputers#101]
Hi there,

I am creating my first app for MineOS, but I've run into a big issue. I'm trying to create a GUI.container as an outside container for a GUI.layout, so I can create a scrollbar and make the GUI.layout scroll up and down (not the elements inside them, but the layout itself). 

On this line,
`local scrollWrapper = window.addChild(GUI.container(1, 10, window.width, window.height - 10))`
I get an error. Although it doesn't specify it's that line, I have debug around the line, and the debug underneath this line doesn't run.

![image](https://user-images.githubusercontent.com/2769013/36576882-7fbd95d6-18b8-11e8-8b30-468afef265e5.png)

(The error leads to https://github.com/IgorTimofeev/OpenComputers/blob/master/lib/GUI.lua#L262)

I am just wondering how this happens. This is my full code here: https://pastebin.com/WykRj4Nr

Any help would be much appreciated!

Thanks!

Edit: I appreciate the amount of current documentation there is for MineOS. There's no way I'd ever be able to make an app without it. Although it's in Russian, and I obviously don't speak Russian, translating the page is still perfectly understandable and helps a lot. So thanks :D

**Comment by r888800009** [comment]
I downloaded your application but can not execute it. Try change `window.addChild()` to `window:addChild()`

**Comment by StrangeOne101** [comment]
Oh wow. Can't believe I made such an easy mistake. I'm not used to using : for methods so I completely overlooked that. Thanks for fixing it, and thanks for putting up with my ignorance lol.

Issue closed.
