### ISSUE TITLE
Не работает App Store

### ISSUE THREAD

**Issue by localChicken** [IgorTimofeev/OpenComputers#106]
![screen shot 2018-04-01 at 8 23 40 am](https://user-images.githubusercontent.com/34812367/38174681-06714ac0-3586-11e8-91a7-23449d19d1fb.png)

**Comment by fgRuslan** [comment]
Эт какая-то хуйня с CloudFlare'ом. У тебя случайно нет прокси или типо того?

**Comment by IgorTimofeev** [comment]
@fgRuslan Не-не, эт я зарядочку маман для планшета отдал, магаз атдахнул))00
