### ISSUE TITLE
Частенько кидает сюда с ошибочкой (attempt to call a nil value (method 'select'))

### ISSUE THREAD

**Issue by tasatko** [IgorTimofeev/OpenComputers#107]
Если добавить условие на обжэкт != нил, это поможет?

https://github.com/IgorTimofeev/OpenComputers/blob/9acfc6ec35b55870c0e0541d5f99a0e3bfdcdcea/lib/GUI.lua#L1592

**Comment by IgorTimofeev** [comment]
Уже пофиксил, спасибо. Название метода было некорректное
