### ISSUE TITLE
[Вопрос. Не по MineOS] Нумерация слотов жестких дисков?

### ISSUE THREAD

**Issue by sziberov** [IgorTimofeev/OpenComputers#110]
Спрошу тут, бо не ебу где можно еще, и у тебя, бо все остальные - затупки.

Как считаешь, стандартными средствами мода можно сделать как в реале SATA нумерацию портов для подключенных накопителей? Хочу запилить BIOS на EEPROM с расшириным до 16, а того и больше KB, местом, а при отсутствии данной фичи такая задача кажется невозможной. Можно бы было считывать все ID жд, флоппи и т.д., запоминать в файл и таким макаром потом пользоватся этим, но это даже звучит убого, не говоря уж о том что сей файл тоже должен где то храниться.

**Comment by sziberov** [comment]
setData() это интересно, надо будет глянуть.

Переписывать весь код не получится. Он уже больше оригинального, а тот в свою очередь и так не маленький, хоть и бесполезный.

Флопик наверно больно по костыльному, правда как замена CMOS достаточно вместительный вариант.

---

Вот эту хрень имел ввиду:
![sata2](https://user-images.githubusercontent.com/7362968/39592763-6ac88e40-4f10-11e8-8ba5-fc27c55751c1.jpg)
![imag0322](https://user-images.githubusercontent.com/7362968/39592774-7146e384-4f10-11e8-8b5a-94b5ad7d35e7.jpg)

**Comment by IgorTimofeev** [comment]
Рили не ебу, ЧТО ты от меня хочешь: на предоставленных фотках имеются порты для подключения, а также перечень дисков в биосе, только и всего. Что конкретно тебе с ними надо сделать-то? Вывести на экран в виде списка? Это пять строк кода:

```lua
local counter, gpu = 1, component.proxy(component.list("gpu")())
for address in component.list("filesystem") do
  gpu.set(1, counter, "Мой пиздатый диск #" .. counter .. ": " .. address)
  counter = counter + 1
end
```

И, надеюсь, ты используешь [минификатор](https://mothereff.in/lua-minifier) для преодоления лимита в 4 Кб?

**Comment by sziberov** [comment]
Самое главное по какому то определенному порядку, а не просто так. Данный код выдает рандомно упорядоченный лист при каждом ребуте. Может сортировать его по алфавиту и писать в импровизированный CMOS? И хранить до изменения кол-ва/типа устройств, дав юзеру в любой момент самому менять его при желании. 

До минификатора чет не додумался, основной упор шел на удобство кода. Когда что то стоящие получится, тогда наверно будет смысл оценить его работу.

**Comment by IgorTimofeev** [comment]
Я же написал решение данной проблемы выше. При первом старте биоса получаешь список адресов файловых систем, сейвишь его в аббревиатурном виде через eeprom.setData(). Далее через гуишку уже меняешь приоритет (и порядок аббревиатур) так, как требуется. Профит, мяу?

**Comment by sziberov** [comment]
Все так, я только добавил про алфавит.

**Comment by sziberov** [comment]
Все так, я только добавил про алфавит.

**Comment by codename684** [comment]
Ебать у вас тут коды
