### ISSUE TITLE
Function paste

### ISSUE THREAD

**Issue by Cinobi** [IgorTimofeev/OpenComputers#112]
Вот такая вот красота при попытке копировать что-либо в Minecode ide с "внешнего", хехе, буфера обмена.
![2018-05-11_22 41 35](https://user-images.githubusercontent.com/25028786/39943720-9edbae80-556c-11e8-91bb-d0ff4dd2c361.png)

**Comment by IgorTimofeev** [comment]
Ой. Пофиксил, благодарю
