### ISSUE TITLE
Несовместимость c точным режимом экрана

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#26]
Если вызвана функция component.screen.setPrecise(true), то при нажатии на экран в ивенте будут дробные числа, а как ты понимаешь, от этого происходит всякая дичь, например, при вызове контекстного меню в таком случае, текст рисуется на месте, а этот прямоугольник с тенью - нет.

![](https://cloud.githubusercontent.com/assets/15855754/24840172/cc0c8422-1d70-11e7-8c5f-16e55c50ca83.png)
![](https://cloud.githubusercontent.com/assets/15855754/24840173/cc3017fc-1d70-11e7-8c9e-9f145629e321.png)
![](https://cloud.githubusercontent.com/assets/15855754/24840174/cc3c5f12-1d70-11e7-9302-ebe9426fdfa5.png)
![](https://cloud.githubusercontent.com/assets/15855754/24840175/cc42a7aa-1d70-11e7-8cb8-25b2c88527f9.png)

_на месте, сосиска в те**к**сте_
_в потолке открылся люк, ты не бойся - это глюк_

**Comment by Eugene8388608** [comment]
а ещё разобраться надо, как надо правильно округлять эти дроби

**Comment by IgorTimofeev** [comment]
О, интересный баг, спасибо. Фиксану чуть позже, когда допилю многозадачность.

**Comment by IgorTimofeev** [comment]
Исправлено, после запуска каждой программы экран переключается в целочисленный режим.
