### ISSUE TITLE
В коде "until" выделяется, а "repeat" - нет

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#27]
![](https://cloud.githubusercontent.com/assets/15855754/24840329/e598586e-1d73-11e7-84ab-682ee059a664.png)
55 строка

**Comment by Eugene8388608** [comment]
а бшщщрлшр ис а

**Comment by Eugene8388608** [comment]
а ещё мультистрочные комменты не выделяются

**Comment by IgorTimofeev** [comment]
Угу, ща фиксанем. Мультистрочные комменты выделяться не будут, так как подсветка синтаксиса построчная, а не комплексная.
