### ISSUE TITLE
Верните Finder!

### ISSUE THREAD

**Issue by TMihis** [IgorTimofeev/OpenComputers#28]

**Comment by Eugene8388608** [comment]
А ещё сделай иконки на рабочем столе передвигаемыми

**Comment by Eugene8388608** [comment]
Но сейчас Игорь занимается мультизадачностью.

**Comment by TMihis** [comment]
1. Мультизадачность
2. Глюк экрана
3. Проводник

**Comment by IgorTimofeev** [comment]
@TMihis Мультизадачность по факту бесполезна, так как понятие "поток" отсутствует в опенкомпах, потоки лишь симулируются при помощи ивентов, что сильно уменьшает быстродействие компьютера и увеличивает расход памяти на открытые программы. Самое большее, что возможно - это приостановка выполнения текущей задачи для выполнения другой с возможностью переключения между активными задачами, это не шибко скажется на использовании ресурсов ЦП.

Файндер верну позже, если время будет, старая прога слишком говнокодерская, надо переписывать. Хотя я, честно говоря, не вижу никакой разницы между старым файндером и текущей навигацией прямо на рабочем столе - никакого особо полезного функционала, за исключением "избранного", в файндере не было, а оперативки он жрал мама не горюй.

@Eugene8388608 Иконки передвигаемыми можно сделать только через конфигурационные файлы в каждой директории по типу .DS_Store и Thumbs.db, что не кажется мне целесообразным ввиду сильной ограниченности по памяти. Могу сделать это исключительно для баловства без сохранения позиций на ЖД (то бишь, при каждой перезагрузке они будут выровнены по сетке), но это такое, знаешь ли, такое. Займусь лучше практически более полезными делами - например, мультивыделением, массовым копипастингом, архивацией и так далее. Но в любом случае мультитаскинг в приоритете.

**Comment by Eugene8388608** [comment]
Насчёт памяти - в новых версиях мода Computronics появилась плашка памяти, размер которой ограничевается максимально возможной памятью, которая прописана в конфиге опенкомпов (изначально 64 МБ).
Кстати, этот мод добавляет ту самую камеру, к которой ты сделал костыльную прожку.

**Comment by IgorTimofeev** [comment]
@Eugene8388608 Это крайне глупый путь. Если кодер не может писать оптимизированный в плане использования памяти софт - то стоит задаться вопросом: а стоит ли вообще ему писать софт? Дворников и нянек в детсадах нынче не хватает.

Мое личное правило заключается в следующем: если программа вместе с ОСькой использует более 2 МБ оперативки (за редким исключением в виде скриптов, работающих с огромными массивами данных), то она подлежит переписыванию. Уж если у нас 3D-движок с динамическим освещением работает на 2 МБ, то остальной софт и подавно обязан.

**Comment by Eugene8388608** [comment]
А, и ещё, добавь запуск программы с аргументами.

**Comment by IgorTimofeev** [comment]
@Eugene8388608 Угу, без проблем.

**Comment by TMihis** [comment]
@IgorTimofeev можно коды файндера?

**Comment by IgorTimofeev** [comment]
@TMihis Да, без проблем: https://github.com/IgorTimofeev/OpenComputers/tree/master/Applications/Finder

**Comment by TMihis** [comment]
@IgorTimofeev Спасибо!

**Comment by IgorTimofeev** [comment]
@TMihis Усе, не прошло и полгода. Файндер переписан, интегрирован в оську, все дела. Наконец-то ебучий реквест закрыть можн
