### ISSUE TITLE
Ошибка с новым приложением

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#31]
по картинкам всё буит ясно
![](https://cloud.githubusercontent.com/assets/15855754/25279743/26446c5a-26b0-11e7-8289-e69a40b13f3d.png)
![](https://cloud.githubusercontent.com/assets/15855754/25279744/26488650-26b0-11e7-873d-0e530b36e518.png)
добавь иконку для приложений без иконок

**Comment by IgorTimofeev** [comment]
Будет пофикшено при следующем апдейте, спасибо, годная ошибка.

**Comment by IgorTimofeev** [comment]
Пофикшено
