### ISSUE TITLE
сукааааааа

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#35]
![](https://cloud.githubusercontent.com/assets/15855754/25313677/fa3baa3c-283b-11e7-8676-864923f19cf7.png)
![](https://cloud.githubusercontent.com/assets/15855754/25313678/fa419bd6-283b-11e7-9f54-91b77bdbd908.png)

**Comment by Eugene8388608** [comment]
теперь кое у кого анусная и головная боль

**Comment by Eugene8388608** [comment]
хотя

**Comment by Eugene8388608** [comment]
надо это всё скачать самостоятельно

**Comment by Eugene8388608** [comment]
тобишь image.lib и appmarket

**Comment by Eugene8388608** [comment]
верни applications.txt

**Comment by fgRuslan** [comment]
У  меня  тоже  подобные  ошибки,я  сделал  пулл реквест,надеюсь  Игорь  его  скоро  увидит  и  сделает  мердж.Но  вот  изменение  *Applications.txt*  на  *Applications.cfg*  я  ну  **НИКАК**  не  понимаю,ведь  смысл  один  и  тот  же...

**Comment by Eugene8388608** [comment]
а чо с пикчами делать?

**Comment by fgRuslan** [comment]
Хм,я думаю,что  у  тебя  не  обновился  image.lua,незнаю,давай  дождёмся  Игоря.Щас  ему  в  вк  напишу..

**Comment by Eugene8388608** [comment]
я либу ещё не обновлял

**Comment by Eugene8388608** [comment]
а что, если я её вручную обонвлю?

**Comment by Eugene8388608** [comment]
не, хуйня
![](https://cloud.githubusercontent.com/assets/15855754/25314491/8cde1efe-284d-11e7-90df-94f6031465c8.png)

**Comment by fgRuslan** [comment]
Вообще  странно,Игорь  пздц  затупил....

**Comment by Eugene8388608** [comment]
зачем модули декодирования вообще выпихивать из либы в отдельные файлы?

**Comment by IgorTimofeev** [comment]
@fgRuslan  Во разорались, ебаный рот. Переименование Applications давно хотел сделать, **хочицца** мне, ну. Аппмаркетом сегодня займусь, вчера устал инсталлер оси новый пилить, не до маркета было.

@Eugene8388608 Обновление либы изображений привнесло тонну вкусных фич - в первую очередь, поддержку кастомных модулей для загрузки форматов. То бишь, если кто-то хочет накодить собственный формат пикч, то достаточно всего лишь оформить его в качестве модуля и подгружать в image-либу. Все остальные методы по типу траспонирования, отражения, обрезки и прочего остались на месте, это по сути универсализация формата изображения, сделанная с целью минимизации хаванья оперативки. Ну, и собственный убер-уебаторско-сжатый метод кодирования добавили, куда ж без этого.
