### ISSUE TITLE
converter из png,jpg в OCIF4

### ISSUE THREAD

**Issue by FluttyProger** [IgorTimofeev/OpenComputers#4]
Сделай, пожалуйста) А то приходится сначала через конвертер в OCIF1 переделывать, а потом в майне в OCIF4

**Comment by IgorTimofeev** [comment]
Жутко лень, если честно. По сути 1 OCIF крайне легко читать и записывать, поэтому выбрал именно его за основу, с четвертым пришлось бы изрядно повозиться. Так что сорре(

**Comment by FluttyProger** [comment]
Я уже давно свой написал))

**Comment by IgorTimofeev** [comment]
@FluttyProger Вот и славненько, ога
