### ISSUE TITLE
Выделение осталось ýöбаным

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#41]
![](https://cloud.githubusercontent.com/assets/15855754/25593963/855d68ee-2ec7-11e7-920c-eaa8595bf014.png)

**Comment by Eugene8388608** [comment]
кек
![](https://cloud.githubusercontent.com/assets/15855754/25594045/cadaf6ac-2ec7-11e7-9baf-c8ec5ade692e.png)

**Comment by IgorTimofeev** [comment]
Исправлено, ска
