### ISSUE TITLE
А как отсюда выйти?

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#44]
![](https://cloud.githubusercontent.com/assets/15855754/25815231/96b48ce2-3428-11e7-9862-355c5a99505d.png)

**Comment by Eugene8388608** [comment]
А, вот ещё что, добавь возможность просмотра полного имени файла\папки. Т.е. при клика на имя выведется в том месте строчка с полным именем.

**Comment by IgorTimofeev** [comment]
На пустое место кликаешь - и выходишь. Надо поочевиднее сделать систему, да. Просмотр полного имени есть в свойствах на ПКМ

**Comment by Eugene8388608** [comment]
А вот в том то и дело, что кликаю, а не выходит.

**Comment by IgorTimofeev** [comment]
@Eugene8388608 Странно, чи шо, у меня все заебись. Все равно сейчас ось перекоживаю - гляну заодно, че там и как

**Comment by IgorTimofeev** [comment]
Рили норм все, ну. Ввел имя - автоматом закрывается, если такого файла не существует. Если существует - вводи норм имечко. Чо не так?

**Comment by Eugene8388608** [comment]
@IgorTimofeev а если передумал?

**Comment by IgorTimofeev** [comment]
@Eugene8388608 Ну лох, чо. Переименовывай, чо. Мне так гораздо удобнее, поэтому делаю так, как считаю нужным.

**Comment by IgorTimofeev** [comment]
Усе, сделал
