### ISSUE TITLE
Помогите пж

### ISSUE THREAD

**Issue by Roma1825** [IgorTimofeev/OpenComputers#45]
Есть проблема при загрузке installera типа "возьмите CPU в свои руки и переключите на lua 5.2"мод последней версии (свежак) так сказать.Что делать подскажите а.

**Comment by Roma1825** [comment]
И вопрос может ли бить что при проверке антивирус не дал точную инфу по поводу какая lua у меня тогда куда вставлять файл оболочки можно ли кинуть на разные ж-диски ?

**Comment by IgorTimofeev** [comment]
Ебучий ж насос, к пояснению такого меня жизнь не готовила. Возьми ебучий айтем процессора в ебучем мире майнача, нажми ебучую правую кнопку мыши и переключи его тем самым на ебучий Lua 5.2.

**Comment by Eugene8388608** [comment]
@Roma1825 ну ты канещна дибииииил.
могбысделатьточтосказали

**Comment by Eugene8388608** [comment]
антивирус нихуя не мог сделать с кубычОм

**Comment by Roma1825** [comment]
Мда попросил помочь а получил совет который сделал 10 рас может 12 короче вот в чом прикол у меня в майне все мири создаются как сервера а для правильной работы и сохранения прогресса на пк после вигрузки чанка нужна такая фича как ERIS она встроена в мод для сингл игры а для функционала на серверах нужно отдельно ставить в систему.Кстати если у тебя бесплатный антивирус и без фаервола и сканера сетевих протоколов подключения то конечно при виполнении и скачивания установщика и другой фигни он ничё тебе не скажет.

**Comment by Roma1825** [comment]
Это связано через что ти майн запускаеш т.к я через тлаунчер (а я так думаю что если я установлю бес лунчера то ничё не будит и всё пройдёт гладко,

**Comment by IgorTimofeev** [comment]
@Roma1825 Если ты хочешь подробной помощи, а не "советов, которые сделал 10 раз", то описывай проблему во всех деталях с перечислением испробованных вариаций. С какой ебучей пизды я должен проссать, что ты таковые действия уже совершал?

Далее по теме: как вариант - в конфиге мода у тебя выставлено принудительное использование LuaJ в обход Eris, отключение этого параметра решит проблему. Но вообще с хуя ли ты задаешь подобные вопросы в репозитории человека, никак не связанного с разработкой мода?
