### ISSUE TITLE
Извените,

### ISSUE THREAD

**Issue by Roma1825** [IgorTimofeev/OpenComputers#46]
Может быть я вопрос не правильно построил и что-то не сказал во-первых мне при запуске пишет исходняки не доступны (т.е библиотеки не доступны и пк после вигрузки чанка перезагружается можэт именно в этом и проблема почему я не могу свичнуть на LUA 5.2) кстате брал и нажимал на л клавишу мыши ещё до моего вопроса но ничё не присходило а архитектура LUAJ.

**Comment by Eugene8388608** [comment]
ты хоть русский сначала выучи, потом программированием занимайся

**Comment by Eugene8388608** [comment]
а то внатуре нихуя не понятно

**Comment by Roma1825** [comment]
НУ извините объясняю исходные библиотеки недоступны как мне это исправить я просто думаю что именно и-за этого я не могу переключить на другую версию lua и да я в курсе что дабы переключить нужно взять и нажать правую кнопку мыши обзор смотрел поэтому знаю.

**Comment by Roma1825** [comment]
Играю в сингл поэтому скорее всего ERIS мне не нужно ставить.

**Comment by Eugene8388608** [comment]
русский учиииии

**Comment by Eugene8388608** [comment]
а то пишешь какой-то набор несвязаных никак слов

**Comment by Roma1825** [comment]
я в Украине поэтому не очень владею

**Comment by Eugene8388608** [comment]
ну хоть что-то на украине не запретили

**Comment by Roma1825** [comment]
Хаааа лол у нас это уже обошли ну по поводу вк и мейл ру

**Comment by Roma1825** [comment]
НУ так как мне исправить проблему при запуске мира мод в чате пишет "Исходные библиотеки Lua не доступны,,,," И поэтому я не могу сменить версию Lua к 5.2 я уже не много разобрался что к чему.

**Comment by Roma1825** [comment]
Что мне делать ?

**Comment by Roma1825** [comment]
Игорь,может вы мне мне поможете я реально не шарю как этот мод работает поэтому я не знаю как исправить ошибку.

**Comment by Roma1825** [comment]
Ок буду ждать ответа так-как я очень всё таки попробывать эту оболочку.И да,вопрос, новые приложения кидать в папку Application да ?

**Comment by Eugene8388608** [comment]
блин

**Comment by Eugene8388608** [comment]
чувак

**Comment by Eugene8388608** [comment]
кнопку обновления найди

**Comment by Roma1825** [comment]
Ты тип прыкалываешся на сайте для 1.7.10 дают старую версию.

**Comment by Roma1825** [comment]
Новую не дают типа авто-обновление вот только его нету.

**Comment by Eugene8388608** [comment]
да обновления в этой оси

**Comment by Eugene8388608** [comment]
а не мода

**Comment by Roma1825** [comment]
Ем.... чел какую какую ось ты имееш ввиду

**Comment by Roma1825** [comment]
Я не очень в этом шарю просто дай ссылку иле скажи что делать

**Comment by Roma1825** [comment]
Если поможэш буду благодарен.

**Comment by Eugene8388608** [comment]
Ты говорил про новые приложения, как их получить. так вот. заходи в майн, в свой комп с MineOS, в левом верхнем углу будет кнопка MineOS, нажимаешь, в контекстном меню выбирай пункт Обновления. Дальше надеюсь разберёшься.

**Comment by Roma1825** [comment]
Я его ещё не поставил всё ещё проблема  с исходными библиотеками Lua мод их не видит а как заставить видеть я хз если честно может написать команду с расположением библиотеки иль что делать.

**Comment by Roma1825** [comment]
Просто друг поставил и хочет ПО обновить.

**Comment by Roma1825** [comment]
Поэтому и спросил.

**Comment by Eugene8388608** [comment]
а ты с правой кнопки попробуй

**Comment by Roma1825** [comment]
Не работает сколько рас говорил я это ищё перед тем как вам написать с проблемой.

**Comment by Eugene8388608** [comment]
блин не то написал

**Comment by Roma1825** [comment]
Я не в курсах может а OpenOS нужно прописать иле создать и мод сам увидит.

**Comment by Roma1825** [comment]
Что это вообще за "Исходные библиотеки Lua"

**Comment by Eugene8388608** [comment]
У тебя из-за LuaJ не переключается на Lua 5.2. Как это исправить? Надо зайти в всратую конфигурацию мода и отыскать пункт, где выбирается движок Lua: LuaJ или более проприетарный (сделанный для более узких целей) движок, который накодил сам автор мода. И надо это переключить. Потом в майначе попробовать переключить процессор.

**Comment by Eugene8388608** [comment]
А конфиг длинный.

**Comment by Roma1825** [comment]
Ок сейчас попробую

**Comment by Roma1825** [comment]
А где эта конфигурацию в самом моде тоесть нужно открыть мод как архив и искать там?Просто хочю уточнить чтобы не трать наше время просто модов у меня много изза етого майничь долго грузит несмотря на то что ПК не слабый.

**Comment by Roma1825** [comment]
Слушай а как скрины добавлять

**Comment by Eugene8388608** [comment]
скрины потом скажу

**Comment by Roma1825** [comment]
![bandicam 2017-05-21 19-27-54-890](https://cloud.githubusercontent.com/assets/28810000/26285597/aad177ac-3e5b-11e7-84b5-40d8d8b19685.jpg) Всё я понял таааак ем что делать

**Comment by Eugene8388608** [comment]
Не, конфиг находится в папке майна

**Comment by Eugene8388608** [comment]
в папке config

**Comment by Roma1825** [comment]
Спасибо сейчас

**Comment by Roma1825** [comment]
![bandicam 2017-05-21 19-32-50-984](https://cloud.githubusercontent.com/assets/28810000/26285638/38a3bcb6-3e5c-11e7-95b8-4a46f07c643d.jpg) Он?

**Comment by Roma1825** [comment]
Ееем тут много всего

**Comment by Roma1825** [comment]
Так конфиг тот но скажы хоть что нибудь из текста я скопирую и сделаю поиск по фразе

**Comment by Roma1825** [comment]
# Whether to make the Lua 5.3 architecture available. If enabled, you
      # can reconfigure any CPU to use the Lua 5.3 architecture.
      enableLua53=true тоисть мне нужно написать false и всё

**Comment by Eugene8388608** [comment]
не там должно быть где-то LuaJ

**Comment by Roma1825** [comment]
Forces the use of the LuaJ fallback instead of the native libraries.
    # Use this if you have concerns using native libraries or experience
    # issues with the native library.
    forceLuaJ=false     Ето оно

**Comment by Eugene8388608** [comment]
да, вроде оно
там изначально что стояло?

**Comment by Roma1825** [comment]
false

**Comment by Eugene8388608** [comment]
блэд

**Comment by Eugene8388608** [comment]
я не знаю чо у тя там творится

**Comment by Roma1825** [comment]
вот ищё один конфиг

**Comment by Roma1825** [comment]
# Whether to always register the LuaJ architecture - even if the native
    # library is available. In that case it is possible to switch between
    # the two like any other registered architecture.
    registerLuaJArchitecture=false

**Comment by Roma1825** [comment]
Да ето тот конфиг если что ето первод # Всегда ли регистрировать архитектуру LuaJ - даже если родной
    Доступна библиотека #. В этом случае можно переключаться между
    # Эти два, как и любая другая зарегистрированная архитектура.
    registerLuaJArchitecture = ложь

**Comment by Eugene8388608** [comment]
там изначально что

**Comment by Roma1825** [comment]
ну ложь

**Comment by Eugene8388608** [comment]
блэээээээд

**Comment by Eugene8388608** [comment]
попробуй на последней версии мода. самой

**Comment by Roma1825** [comment]
Ок скинь я прост не могу найти оф сайт иле что-то подобное

**Comment by Eugene8388608** [comment]
ок

**Comment by Eugene8388608** [comment]
_коок_

**Comment by Eugene8388608** [comment]
[вот](https://mods.curse.com/mc-mods/minecraft/223008-opencomputers)

**Comment by Roma1825** [comment]
кстати для какой версии майнича

**Comment by Roma1825** [comment]
У меня 1.7.10

**Comment by Roma1825** [comment]
Какую кнопку обновления

**Comment by Eugene8388608** [comment]
майнач 1.10.2

**Comment by Eugene8388608** [comment]
на него многие моды уже перешли

**Comment by Eugene8388608** [comment]
почти все

**Comment by Roma1825** [comment]
последняя версия  именно 1,7,10 версия мода 1,6,2,12

**Comment by Eugene8388608** [comment]
1.10.2

**Comment by Eugene8388608** [comment]
ищи

**Comment by Roma1825** [comment]
1,10,2 ето версия для какого майна а текст рядом версия мода

**Comment by Eugene8388608** [comment]
1.10.2 майнач

**Comment by Eugene8388608** [comment]
т.е. тебе придётся качать майнааааач

**Comment by Eugene8388608** [comment]
а я сижу с андроида на компе

**Comment by Eugene8388608** [comment]
скрин ща кину

**Comment by Eugene8388608** [comment]
![screenshot_20170521-200733](https://cloud.githubusercontent.com/assets/15855754/26285899/31f6016c-3e61-11e7-86f5-bb0e2f56a7c0.png)

**Comment by Roma1825** [comment]
щя щя 
к меня т лаунчер щя скачаю

**Comment by Eugene8388608** [comment]
лан я занят. пока

**Comment by Roma1825** [comment]
Короче походу у меня нет исходной библиотеки lua вот почему мод её не видит

**Comment by Roma1825** [comment]
оК КАК ЕЁ СОЗДАТЬ

**Comment by TMihis** [comment]
Попробуй переустановить мод. 
[OpenComputers 1.7.10](https://mods.curse.com/mc-mods/minecraft/223008-opencomputers/2385983)

**Comment by Roma1825** [comment]
Пробовал 3 раза нечего  не происходит у меня нет исходных библиотек Lua,а что это я хз как создать доже не знаю короче буду в инете искать может и язык прийдётса учить.

**Comment by Roma1825** [comment]
Так сказали конфиг мода есть строка где написано всегда подключать исходные библиотеки я поставил на true надеюсь поможет.

**Comment by Roma1825** [comment]
Короче нужно найти иле скачать иле создать накодить , короче мне нужна библиотека Lua у кого есть програмнная среда Lua 5.2 ? Скинте в Яндекс диск я скачаю если есть версия не ниже 5.2.3 просто на форумах часто пишут эту версию как самую актуальную а скачать я не могу найти где дают только tar архив а в нём только часть все что нужно другое более старой версии.

**Comment by TMihis** [comment]
А можно сборку зальёшь на облачный диск? Я посмотрю и поправлю.

**Comment by sziberov** [comment]
Омг, зачем вы этому валенку вообще пытаетесь помочь? Он че вам заплатит?

**Comment by Eugene8388608** [comment]
он не заплатит
я тебя кстати на ютубе видел

**Comment by sziberov** [comment]
Я тоже себя много где видел.

Так вот если "не заплатит", то на кой член тратить стоко время и терпения на конченного нуба? Он даже не сразу выкупил где конфиг мода хранится, а как нажать Ctrl+F в нем, ввести LuaJ, и посмотреть чтоб везде стояло false он вряд ли и с подробным разъяснением поймет.

**Comment by Eugene8388608** [comment]
@Roma1835 кстати, а хера ты лез в эти опенкомпы, если языка даже не знаешь?

**Comment by IgorTimofeev** [comment]
@sziberov Да рот ебал таких говножуев, ежжи. Держите кису, шоб жиза приятнее жилась:

![2017-05-23 1 28 41](https://cloud.githubusercontent.com/assets/11760002/26330953/2d94a744-3f57-11e7-8de0-8467ce4f5f92.png)

**Comment by Eugene8388608** [comment]
пасиба)
