### ISSUE TITLE
Говно

### ISSUE THREAD

**Issue by fgRuslan** [IgorTimofeev/OpenComputers#47]
Исправь  эту  херню
![image](https://cloud.githubusercontent.com/assets/11362683/26282681/bce79666-3e1e-11e7-9063-83f53d733667.png)
![image](https://cloud.githubusercontent.com/assets/11362683/26282693/e0f7bc2a-3e1e-11e7-9fd2-e597afb51e56.png)

**Comment by fgRuslan** [comment]
P.S.  если  надо  закрыть  issue,можно  сделать  это  так:
* Исправляешь баг,который там описан
* Пишешь коммит,в комментарии  к  которому  имеется Fix или Fixed и номер issue
* Например: **git commit -m "Исправлены ошибки, Fix #47"**

**Comment by TMihis** [comment]
Похуй на название.

**Comment by IgorTimofeev** [comment]
Похуй на эту хуйню, других забот по горло, не хватало еще из-за каждой стилистической неточности хуем очко рвать. 

Если надо закрыть иссуе-хуюе, то я нажимаю кнопку "Close", на подробное комментирование и пояснение деталей фикса похуй. Если кому-то на это не похуй, то мне на его, безусловно, важное мнение также похуй, как и на комментирование. Чего мне тут определенно не хватало - так это йоба-сенсеев по работе с гитом-хуитом
