### ISSUE TITLE
ти шо

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#49]
![](https://cloud.githubusercontent.com/assets/15855754/26423004/94b336ec-40d4-11e7-93c4-a1a92e9b1a2a.png)

**Comment by IgorTimofeev** [comment]
Да ось подготавливаю к оконному интерфейсу, это баг гуишной функции, исправлю потом.

**Comment by Eugene8388608** [comment]
это кстати только в этой проге, в вк такого нет

**Comment by IgorTimofeev** [comment]
Эта хуйня есть только там, где я вручную в коде ее указал. По сути раньше делала цветной заголовок для окна, визуально неплохо выглядело. Сейчас чутка по-другому гуйку переписал, убрал эту фичу, заменив более важной

**Comment by fgRuslan** [comment]
@Eugene8388608 вообще то она есть почти везде,где в ней есть доп. параметры,не только в Stargate.

**Comment by Eugene8388608** [comment]
а
ну ок

**Comment by IgorTimofeev** [comment]
По большей части пофикшено
