### ISSUE TITLE
Проблемы с гуихой

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#50]
В ВК после неверно набранного логина/пароля кнопка ОК не отжимается.
В нём же в диалогах (может быть ещё где) половина экрана остаётся списком диалогов.
Нижние панели в том же ВК и майнкоде сломаны.

Это, наверно, не все проблемы, надо искать.

**Comment by IgorTimofeev** [comment]
Угу, тоже заметил. Над потом фиксить

**Comment by IgorTimofeev** [comment]
Пофикшено
