### ISSUE TITLE
Баг с отрисовкой обоев

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#56]
Хай тупо по середине будут.

**Comment by IgorTimofeev** [comment]
Хаю хай, блядь. Гоу скрин что ли, если не впадлу. По логике обои нормас так должны растягиваться по размеру моника

**Comment by Eugene8388608** [comment]
Скрин не могу, увы.
А вообще дело было так: я по собственной тупости решил поставить в качестве обоев, догадайся, что? Правильно: иконку приложения. Вроде ничо так. Всё растягивается как надо. Но когда я начал искать нормальные обои, я заметил, что на этой обоине стали отпечатываться все файлы и папки. Я вот это имел ввиду.

**Comment by Eugene8388608** [comment]
хотя скрин ща кину.

**Comment by Eugene8388608** [comment]
![](https://cloud.githubusercontent.com/assets/15855754/26695873/27532a0c-4715-11e7-8983-8e801ae69b97.png)

**Comment by IgorTimofeev** [comment]
Ух ты, интересный баг. Судя по всему, если ставить в качестве обоев картинку с имеющимися прозрачными пикселями, то они не будут перекрывать содержимое буфера. Да, очень интересно. Пофиксить легко, но надо ли? А, а?

**Comment by fgRuslan** [comment]
А когда у меня такое было, я думал это я тупилXD

**Comment by Eugene8388608** [comment]
Можно за обою поставить фон.
А можно ищо добавить другой режим фиттинга обоев: по центру, т.е. ничего не будет растягиваться, а ставиться прст по центру.
Или замостить(заполнить экран копиями одной и той-же пикчи).

**Comment by IgorTimofeev** [comment]
@Eugene8388608 Да, мысль. Пусть повисит пока иссуя, надо с гуйкой доебаться, кончить - и за обойки приняться

**Comment by IgorTimofeev** [comment]
Так, заебенил норм опции по растягиванию-хуягиванию обоек, ну, и фон по дефолту системный рисуется:

![2017-06-04 11 37 50](https://cloud.githubusercontent.com/assets/11760002/26760176/a5a1742a-491a-11e7-8333-004be840d57a.png)
