### ISSUE TITLE
Пызда с майнкодом и осью

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#61]
![image](https://user-images.githubusercontent.com/15855754/26876118-6666cdee-4b8d-11e7-9491-a6211b1bb1db.png)

**Comment by Eugene8388608** [comment]
Ошибки в майнкоде. А ещё в отладчике ошибок оси.

**Comment by Eugene8388608** [comment]
Кстати, док можно сделать лучше, если по краям будут вот эти символы:
``
◢◣
``

**Comment by fgRuslan** [comment]
@Eugene8388608 

> Кстати, док можно сделать лучше, если по краям будут вот эти символы:◢◣

Мне сделать пулл реквест с этими символами?

**Comment by Eugene8388608** [comment]
@fgRuslan как хочешь

**Comment by IgorTimofeev** [comment]
@Eugene8388608 Случайная ошибка. Видимо, у тебя не обновилась либа doubleBuffering, там как раз эти фичи захуячены. Щас сменю версию на поновее
