### ISSUE TITLE
Drag'n'Drop в студию

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#63]
![image](https://user-images.githubusercontent.com/15855754/27005057-b118ab3a-4e1e-11e7-8617-7dc96d76437c.png)

**Comment by IgorTimofeev** [comment]
Бля, впадлу, пиздец. Я уж было понадеялся на пулл реквест готовый хд

**Comment by Eugene8388608** [comment]
@IgorTimofeev оно само

**Comment by IgorTimofeev** [comment]
Крч, ебанул тебе драг-дроп

![2017-06-11 14 45 36](https://user-images.githubusercontent.com/11760002/27010753-c5bb020e-4eb4-11e7-998d-8f02547f00ec.png)

![2017-06-11 14 45 17](https://user-images.githubusercontent.com/11760002/27010754-d1c200c0-4eb4-11e7-90c0-200fa113941f.png)
