### ISSUE TITLE
GUI.error

### ISSUE THREAD

**Issue by Avaja** [IgorTimofeev/OpenComputers#65]
Хотелось бы иметь возможность менять название под жёлтым треугольником.

**Comment by IgorTimofeev** [comment]
Ну прям даж не знаю, прям очень хотелось бы? Прям-прям?

**Comment by fgRuslan** [comment]
А если оно будет больше 4 символов?))

**Comment by IgorTimofeev** [comment]
Ну ладн, раз не очень хотелось бы... тогда... наверное... мяу.
