### ISSUE TITLE
Падает, если путь к обоям не валиден

### ISSUE THREAD

**Issue by DrizztDoUrden** [IgorTimofeev/OpenComputers#66]
В общем-то, если открыть настройку обоев, кликнуть на поле для ввода (оно очистится) и кликнуть на пустое место, то MineOS падает и в последствии не запускается.

**Comment by fgRuslan** [comment]
Меня тоже заебало

**Comment by IgorTimofeev** [comment]
Пофикшено
![2017-08-06 14 06 26](https://user-images.githubusercontent.com/11760002/29002674-79278c0a-7ab0-11e7-9bcb-04071e7056c4.png)
