### ISSUE TITLE
Ошибка после установки

### ISSUE THREAD

**Issue by V300** [IgorTimofeev/OpenComputers#72]
Установка проходит нормально. После ребута ошибка вида:

unrecoverable error
bios:59 [string "local background, foreground, logoColor = 0xD...":122: attempt to index field 'preload' (a nil value)
stack traceback:
machine:756: in function '__newindex'
[string "local background, foreground, logoColor = 0xD..."]:122: in main chunk
[C]: in function 'xpcall'
bios:58:  in function 'bt'
bios:120: in function 'waitForAlt'
bios:128: in main chunk

Майн 1.7.10

**Comment by Eugene8388608** [comment]
какая версия опенкомпов?

**Comment by V300** [comment]
OC 1.6.2.1060-dev
Да, много раз, и на сервере и в креативе.

**Comment by Eugene8388608** [comment]
хз че у тя ворится

**Comment by Eugene8388608** [comment]
вообще не сразу понял, где такую версию откопал.

**Comment by V300** [comment]
Админ видать не обновляет версию на сервере, хотя до вайпа все ставилось. Попрошу обновить. Потом отпишу.

**Comment by IgorTimofeev** [comment]
Хуй знает, хуй знает. Закрываю пока иссую, все заебок, вродь
