### ISSUE TITLE
English Documentation

### ISSUE THREAD

**Issue by veso266** [IgorTimofeev/OpenComputers#73]
Hi I love MineOS but creating custom apps for it was a bit of a pain because GUI documentation is in Russian which I don't understand so if someone could translate at least GUI.md into English it would be great

BTW: when trying some example stuff I can't seen to get out of an app if I draw Fullscreen Container anyone knows how to draw content Menu over it?

```lua
local buffer = require("doubleBuffering")
local GUI = require("GUI")

buffer.clear(0x2D2D2D)

--- Container Test ----
local mainContainer = GUI.fullScreenContainer()
mainContainer:addChild(GUI.panel(1, 1, mainContainer.width, mainContainer.height, 0x2D2D2D))

mainContainer:addChild(GUI.label(2, 2, mainContainer.width, mainContainer.height, 0xFFFFFF, "Centered text")):setAlignment(GUI.alignment.horizontal.center, GUI.alignment.vertical.center)

mainContainer:draw()
buffer.draw(true)
mainContainer:startEventHandling()
--- Container Test ----


--- ContextMenu Test -----
local contextMenu = GUI.contextMenu(2, 2)

contextMenu:addItem("Exit").onTouch = function()
	ecs.error("TEST")
end

contextMenu:show()
--- ContextMenu Test -----
```

PS: I Think it would be great if MineOS would have some English, Russian Forum where people could talk about it, what the've written for it and have fun

**Comment by IgorTimofeev** [comment]
@veso266 My English is very bad for full translation of documentation. Maybe somebody... someday...

In your code example you are trying to call context menu outside main event handler loop. The program is still running and waiting for some events in this function:

```lua
mainContainer:startEventHandling()
```

Try something like this to call context menu during event processing:

```lua
-- Add a button to main container
local myButton = mainContainer:addChild(GUI.button(2, 2, 20, 3, 0xFFFFFF, 0x0, 0xAAAAAA, 0x0, "I'm a button"))
-- Add a callback-function to button that shows context menu when touching it
myButton.onTouch = function()
	local contextMenu = GUI.contextMenu(2, 2)
	contextMenu:addItem("Exit").onTouch = function()
		GUI.error("TEST")
	end
	contextMenu:show()
end
```
