### ISSUE TITLE
Переименования файлов

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#76]
Или не переименуй
Или сделай систему смены имён с обновлениями

а то как-то не комильфо потом из винды искать и изменять имя вручную

**Comment by IgorTimofeev** [comment]
В чем проблема? Весь мой софт автоматически обновляется под новые версии файлов. За чужой я ответственности не несу, благо оська в бете

**Comment by Eugene8388608** [comment]
у меня ось ссылается на конфу Properties.cfg, которой у меня сразу после обновы не было, а был только Settings.cfg

**Comment by Eugene8388608** [comment]
вот его я и переименовал

**Comment by Eugene8388608** [comment]
/MineOS/System/

**Comment by IgorTimofeev** [comment]
А-а-а, щит, ты попал под раздачу невовремя, видимо. Ща доделаем все - и должно автоматически хуяриться
