### ISSUE TITLE
Веб интерфейс для AppMarket

### ISSUE THREAD

**Issue by GeorgeBgk** [IgorTimofeev/OpenComputers#79]
Привет, Игорь! Я хочу написать для AppMarket веб интерфейс для разработчиков. Шоб можно было загружать туда приложения и смотреть статистику. Можешь пожалуйста ответить.

**Comment by IgorTimofeev** [comment]
@GeorgeBgk Уже сам пишу, жду доставки малинки для статичного домашнего хоста апача с мускулом. А на данный момент - как ты планировал это реализовать? Через внешний php-скрипт и апи гитхабыча?

**Comment by GeorgeBgk** [comment]
NodeJS + Хост на DigitalOcean

Человек вводит имя репозитория (публичного) и сайт добавляет URL на сервер. AppMarket делает HTTP GET на сервак и получает JSON ответ с приложениями

**Comment by GeorgeBgk** [comment]
Не совсем. Сервер хочу написать на Node.JS, хост дома на супер мега серваке (старый комп с core i5 на котором мой майнкрафт сервер).

Человек заходит на сайт, вводит адрес репы на гитхабыче, имя приложеньки и всякое сопутствуещее типа описания итд. Мой сервак записывает эти данные себе.

Когда человек заходит в AppMarket, AppMarket делает запрос на сервак, получает инфу о приложеньке и адрес репы. Из репы скачивается приложение и устанавливается. Профит

**Comment by IgorTimofeev** [comment]
А, ну как раз нечто подобное и пилю. Так что спасибо за очень щедрое предложение, но нинада <3

**Comment by sziberov** [comment]
@GeorgeBgk чувак, тебе некуда сервак определить чтоле? За 40 грн/мес к примеру можешь файлообменник держать?

**Comment by GeorgeBgk** [comment]
@sziberov wut? хранилище файлов сделать?

**Comment by sziberov** [comment]
@GeorgeBgk Полноценное. С предпросмотром видео/аудио, описании в html, комментарии не хуже тех, что на форуме и т.д.

**Comment by GeorgeBgk** [comment]
@sziberov Чел, у меня есть уже проект. Прога для малинки которая поднимает домашний Google Drive на который можно качать торренты, и так далее.

**Comment by sziberov** [comment]
@GeorgeBgk Домашний GDrive это скучно. И в каком смысле "на который можно качать торренты", ты хочешь торрент-трекер поднять? Для дома? Какой то безперспективняк, если кроме тебя их качать никто не будет. Другое дело воскресить топовый сайт (ex.ua), зря что ли я 10 месяцев его оболочку с нуля писал?

**Comment by GeorgeBgk** [comment]
У меня этот домен забанен, так что не.

**Comment by sziberov** [comment]
@GeorgeBgk Какая разница, забанен или нет? Он все равно откинулся, я же написал. Вот сюда зайди, если хошь узнать что там примерно было - tyt.pp.ua
