### ISSUE TITLE
Attempt to index field 'localization' (a nil value)

### ISSUE THREAD

**Issue by LaughingDragon** [IgorTimofeev/OpenComputers#8]
After a fresh install (several), I receive the following error:
Attempt to index field 'localization' (a nil value)

Minecraft 1.10.2 (Forge)
Opencomputers 1.6
Tier3 Case, Tier 3 CPU, Tier 3 HDD + Tier2 HDD + 3 Tier3 RAID, Tier3 Graphics

![2017-01-24_09 52 42](https://cloud.githubusercontent.com/assets/25347681/22295607/88dbec44-e2e5-11e6-9157-9b3dc77d8632.png)

**Comment by IgorTimofeev** [comment]
Fixed a few days ago, thank you.

**Comment by LaughingDragon** [comment]
What do I need to do to install this fix?
I just used the pastebin install again with the exact same error message after install.

**Comment by IgorTimofeev** [comment]
@LaughingDragon I honestly do not know why this error occurs you. The only time it can happen - is the missing of some fields in the english localization. I have installed english version of OS a few minutes ago - and everything is fine. Sorry.

**Comment by LaughingDragon** [comment]
Just after I posted this it began to work.
I can't think of anything I changed. However, it seems to working fine now.
Thank you so much for making this.
Спасибо
