### ISSUE TITLE
какого члена?

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#80]
![](https://user-images.githubusercontent.com/15855754/31853664-0222cb80-b695-11e7-82c7-d30043e05ae7.png)

**Comment by IgorTimofeev** [comment]
Не ебу, у меня все норм, ставил ось только что с нуля. Ошибка связана с отсутствующей иконкой в ресурсах приложения, либо с отсутствующим файлом, на который ссылается ярлык

**Comment by Eugene8388608** [comment]
лан попробую снести ось и переустановить

**Comment by IgorTimofeev** [comment]
Шо там, шо, усе норм?

**Comment by IgorTimofeev** [comment]
Ой, ну и все. Молчишь(
