### ISSUE TITLE
низя посмотреть содержание пакета

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#81]
![](https://user-images.githubusercontent.com/15855754/31853687-736a0420-b695-11e7-9838-1f6b9f8779ed.png)
![image](https://user-images.githubusercontent.com/15855754/31853702-c08cea4c-b695-11e7-9040-63a043719312.png)

**Comment by IgorTimofeev** [comment]
Ясен хер нельзя, это ж ярлык. Для ярлыков имеется возможность только показывать содержащую папку, а для приложений - уже содержимое пакета. В теории можно заморочиться и сделать рекурсивный анализ содержимого ссылки ярлыка, но тогда они будут грузиться вдвое дольше

**Comment by Eugene8388608** [comment]
эээ стопэ
