### ISSUE TITLE
неправильно названый #82

### ISSUE THREAD

**Issue by Eugene8388608** [IgorTimofeev/OpenComputers#83]
низя посмотреть **содержащую папку**

**Comment by IgorTimofeev** [comment]
Не, ну я поражаюсь рил: у тебя повреждены абсолютно все ярлыки на рабочем столе, т.е. они ссылаются на отсутствующий файл или директорию. С какого волшебного хуя тебе должно быть "льзя" просматривать содержащую папку несуществующих файлов?
