### ISSUE TITLE
Не работает библиотека thread

### ISSUE THREAD

**Issue by AtomicScience** [IgorTimofeev/OpenComputers#85]
При попытке запустить первый пример со страницы официальной документации
(http://ocdoc.cil.li/api:thread)
`local thread = require("thread")
print("Main program start")
thread.create(function(a, b)
print(a)
os.sleep()
print(b)
end, 'A', 'B')
print("Main program end")` 
приложение падает с ошибкой.
![image](https://user-images.githubusercontent.com/17031340/32384195-2456e0f2-c0cb-11e7-82fd-d0901ca07ecb.png)
В чистой OpenOS все шикосно:
![image](https://user-images.githubusercontent.com/17031340/32384259-5e589d40-c0cb-11e7-8d7e-2d332e58a4c2.png)

**Comment by IgorTimofeev** [comment]
Либа thread использует дефолтную OpenOS'овскую либу event. MineOS предоставляет собственную, оптимизированную, где, разумеется, названия переменных иные, т.е. поле handlers_mt банально не существует. Рекомендую вовсе не использовать thread ввиду ее жуткой костыльности и значительного снижения общей производительности

**Comment by AtomicScience** [comment]
Да так, побаловаться хотел

Ну тогда удали thread.lua к хренам и считай пофиксил

**Comment by IgorTimofeev** [comment]
Чому удалять-то, я опенось не трогаю(
А доки есть, папочка ж так и называется:
![2017-11-04 18 39 59](https://user-images.githubusercontent.com/11760002/32406766-9baba1be-c18f-11e7-894f-c4298afe5f83.png)
