### ISSUE TITLE
Прогресс бар

### ISSUE THREAD

**Issue by localChicken** [IgorTimofeev/OpenComputers#93]
Есть ли возможность изменять количество единиц в одном пикселе в прогресс баре, то-есть к примеру есть число 800 и оно вылезает за экран, нужно что-бы прогресс бар оставался по размеру как и с числом 100, но при этом что-бы в нем было 800
![default](https://user-images.githubusercontent.com/34812367/34637847-d5e4ee82-f2cf-11e7-93ea-7d1fc539fc61.png)

**Comment by IgorTimofeev** [comment]
Ну, фичу без проблем впилил - теперь пиксельное значение всегда будет не более 100%, а текстовое останется прежним, так что обнови библиотеку. Но вообще довольно странное пожелание: я бы банально сделал верхней границей прогрессбара максимально возможную температуру реактора, и дело с концом
