### ISSUE TITLE
Частые вылеты и OutOfMemory

### ISSUE THREAD

**Issue by gurland** [IgorTimofeev/OpenComputers#94]
Версия: OpenComputers_MC1.7.10_1.7.0.1085_universal
При работе с ОС очень часто графическая оболочка вылетает в терминал OpenOS.
![2018-01-09_17-13-33](https://user-images.githubusercontent.com/30530987/34727994-46b2549a-f561-11e7-9319-a2a8f93cff96.gif)
При запуске Spinner каждый раз выкидывает ошибку `MineOSCore fatal error: not enough memory`
![2018-01-09_17-15-41](https://user-images.githubusercontent.com/30530987/34728004-4b5a750e-f561-11e7-87c5-f583bb91b94e.gif)

Система чистая, только поставленная. 
Комплектующие 3 уровня
![javaw_2018-01-09_17-20-22](https://user-images.githubusercontent.com/30530987/34728055-749b816a-f561-11e7-8f78-5d74d209ebea.png)

Есть доступ к конфигам сервера.

**Comment by gurland** [comment]
Заметил что чаще всего вылет в терминал последует после частичной прогрузки приложений в AppMarket.

**Comment by IgorTimofeev** [comment]
@gurland Отключай обои, они кушают много памяти. Либо крафти серверную стойку, в которую пихай 4 планки Tier 3.5 RAM
