### ISSUE TITLE
app market account security advice

### ISSUE THREAD

**Issue by r888800009** [IgorTimofeev/OpenComputers#96]
Hi ,I have some ideas that may improve the security of the app market account.
- Encryption password in the database
- Use POST to login and register account
- Send a password change email
- When registering, enter the password twice to verify that it is the same.instead of sending mail containing the password.

thx

**Comment by IgorTimofeev** [comment]
1. They're SHA-512 hash already, what do you mean by "encryption"?
2. Ok
3. Ok
4. No

**Comment by IgorTimofeev** [comment]
Done. Every request parameter now passes as POST-data, added possibility to change password when logged it (e-mail with notification about it will be also sent), added slider to login without remembering password
